if(NOT DEFINED LUAJIT_MAKEFILE)
  message(FATAL_ERROR "LUAJIT_MAKEFILE is required")
endif()

file(READ "${LUAJIT_MAKEFILE}" LUAJIT_MAKEFILE_TEXT)

if(LUAJIT_MAKEFILE_TEXT MATCHES "(^|\n)XCFLAGS[+]?=[^\n]*-DLUAJIT_DISABLE_JIT")
  return()
endif()

string(REPLACE "XCFLAGS=" "XCFLAGS+= -DLUAJIT_DISABLE_JIT" LUAJIT_MAKEFILE_TEXT "${LUAJIT_MAKEFILE_TEXT}")
file(WRITE "${LUAJIT_MAKEFILE}" "${LUAJIT_MAKEFILE_TEXT}")
