if(NOT DEFINED LUAJIT_MAKEFILE)
  message(FATAL_ERROR "LUAJIT_MAKEFILE is required")
endif()

file(READ "${LUAJIT_MAKEFILE}" LUAJIT_MAKEFILE_TEXT)

if(LUAJIT_MAKEFILE_TEXT MATCHES "(^|\n)XCFLAGS[+]?=[^\n]*-DLUAJIT_DISABLE_JIT")
  return()
endif()

set(UPDATED_LUAJIT_MAKEFILE_TEXT "${LUAJIT_MAKEFILE_TEXT}")
string(REGEX REPLACE "(^|\n)(XCFLAGS[+]?=[^\n]*)" "\\1\\2 -DLUAJIT_DISABLE_JIT" UPDATED_LUAJIT_MAKEFILE_TEXT "${UPDATED_LUAJIT_MAKEFILE_TEXT}")

if("${UPDATED_LUAJIT_MAKEFILE_TEXT}" STREQUAL "${LUAJIT_MAKEFILE_TEXT}")
  message(FATAL_ERROR "Could not find XCFLAGS in ${LUAJIT_MAKEFILE}")
endif()

file(WRITE "${LUAJIT_MAKEFILE}" "${UPDATED_LUAJIT_MAKEFILE_TEXT}")
